[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.oxfmt]
command = "oxfmt"
includes = ["*.md"]

[formatter.shfmt]
command = "shfmt"
options = ["-w", "-i", "2", "-s"]
includes = ["*.sh"]
